import type { ReviewFinding, ReviewResult } from "../types.js";

export const COMMENT_MARKER = "<!-- ai-pr-reviewer -->";

const severityIcon: Record<ReviewFinding["severity"], string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "⚪"
};

function escapeTableCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

export function renderReviewComment(result: ReviewResult): string {
  const findings =
    result.findings.length === 0
      ? "No actionable defects were identified in the available diff."
      : [
          "| Severity | Location | Finding |",
          "|---|---|---|",
          ...result.findings.map((finding) => {
            const location = finding.line
              ? `\`${finding.file}:${finding.line}\``
              : `\`${finding.file}\``;
            const detail = [
              `**${escapeTableCell(finding.title)}**`,
              escapeTableCell(finding.explanation),
              finding.suggestion
                ? `**Suggested fix:** ${escapeTableCell(finding.suggestion)}`
                : undefined
            ]
              .filter(Boolean)
              .join("<br>");
            return `| ${severityIcon[finding.severity]} ${finding.severity.toUpperCase()} | ${location} | ${detail} |`;
          })
        ].join("\n");

  const tests =
    result.testRecommendations.length === 0
      ? "No additional tests suggested."
      : result.testRecommendations.map((test) => `- ${test}`).join("\n");

  return `${COMMENT_MARKER}
## AI PR review

**Risk:** ${result.risk.toUpperCase()}

${result.summary}

### Findings

${findings}

### Recommended tests

${tests}

<sub>Generated by AI. Validate findings before making changes.</sub>`;
}
